### ISSUE TITLE
autocomplete not functioning

### ISSUE THREAD

**Issue by nckbgov** [theia-ide/yang-vscode#3]
On mac os x (High Sierra) with java version "1.8.0_151" autocomplete is not functioning. Is there a complete list of requirements in order to have this feature working?

**Comment by JanKoehnlein** [comment]
I published a new version 1.1.1 with an updated language server. Could you try again by uninstalling / re-installing the extension?
Autocomplete isn't available before the language server has started. This can take a few seconds after the opening of the first YANG file. You have to trigger it by pushing CMD-SPACE (CTRL-SPACE on non-Macs).

**Comment by JanKoehnlein** [comment]
No feedback. I close this as fixed.

**Comment by TianliangZ-Fujitsu** [comment]
Is there a way to let the code completion hint automatically pop up instead of having to ctrl+space? Thank you
