### ISSUE TITLE
yang library path

### ISSUE THREAD

**Issue by maxnoto** [theia-ide/yang-vscode#4]
Hi,
I have a project that uses external path for libraries.
I tried to add them to the classpath but I always have the same error:
Couldn't resolve reference to AbstractModule '...'.
There is a way to configure an external path for yang libraries?
Thank you
Max

**Comment by svenefftinge** [comment]
Hi Max,
could you please be clear about what you did and what you expected to happen?

**Comment by maxnoto** [comment]
Hi Sven,
I'm developing a cisco nso package.
All libraries is located in a path outside my project.
Cisco nso include all default yang library during import packages.
When I use "import" keyword the editor obviously can't resolve library modules.

![screenshot](https://user-images.githubusercontent.com/13038601/38352675-43242aa6-38b4-11e8-9842-689164ee5c91.jpg)
I'd like to resolve the library path like the java classpath and take advantage of the editor like source errors and autocomplete functions.
Thank you
Max

**Comment by maxnoto** [comment]
Hi Sven,
Do you have news about my issue ?
thank you

**Comment by svenefftinge** [comment]
ATM all modules need to reside in the workspace. 
Supporting external library pathes (including zips) would be a great addition.

**Comment by JanKoehnlein** [comment]
You can add these libs as yangPath in the yang.settings file in your home folder or in the workspace root now.
Entries can be yang file names, directory names or zip file names (all absolute) in OS specific syntax, separated by the OS specific path separator.

Example

{
    "yangPath": "/path/to/rift.zip:/some/special/my.yang:/some/dir/containing/yang/files",
}

**Comment by Hubro** [comment]
> You can add these libs as `yangPath` in the `yang.settings` file in your home folder or in the workspace root now.
> Entries can be yang file names, directory names or zip file names (all absolute) in OS specific syntax, separated by the OS specific path separator.
> 
> Example
> 
> ```
> {
>     "yangPath": "/path/to/rift.zip:/some/special/my.yang:/some/dir/containing/yang/files",
> }
> ```

This should probably be documented somewhere. I searched for quite a while before I found this issue, and as far as I can tell this is the only place this solution is mentioned.

Also, if possible, it would be great if this setting could be specified in the editor settings. It would increase portability and reduce clutter. For example:

```json
{
    "folders": [
        {"path": "NSO/modules"}
    ],
    "settings": {
        "yang.path": "/home/hubro/nso-4.7/src/ncs/yang"
    }
}
```

**Comment by jbl241987** [comment]
I have a workspace created on windows VSCode but on remote SSH (ubuntu 20). Yangster extension installed but I have the same problem as @maxnoto but I don't yang.settings
