### ISSUE TITLE
Config?

### ISSUE THREAD

**Issue by dfarley1** [theia-ide/yang-vscode#7]
Are there any configuration settings for this extension?  I'd like to turn of the "# references" that are inserted in the editor.
![image](https://user-images.githubusercontent.com/5204693/42719489-fdb515ec-86ca-11e8-85c9-44894f8b3182.png)

**Comment by JanKoehnlein** [comment]
Currently not. This project is just a thin wrapper to run the yang-lsp as a VSCode extension.

**Comment by Hubro** [comment]
@JanKoehnlein Are there any workarounds or hacks that can be used to remove the reference count? I don't need them, so they just add clutter to the editor.

**Comment by JanKoehnlein** [comment]
You can put the following into a file `yang.settings` 
```json
{ "code-lenses": "off" }
```
The file can reside in
- the workspace root
- the project root
- `<your user home>/.yang/`

**Comment by Hubro** [comment]
@JanKoehnlein Perfect, thanks :D

It might be useful for other people if some information about `yang.settings` was included in the readme, especially `yangPath` and `code-lenses`.
